version: '3.9'

services:
  pythonapp:
    container_name: pythonapp
    image: pythonapp
    depends_on:
      - db
    build: .
     # context: .
      #dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: on-failure
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5001:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    volumes: 
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
